services:
  - type: web
    name: netflix-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        scope: run
        value: ""
      - key: JWT_SECRET
        scope: run
        value: "prod-secret-change-me"
      - key: JWT_EXPIRES_IN
        scope: run
        value: "24h"
      - key: NODE_ENV
        scope: run
        value: "production"
